on: [push, pull_request]

jobs:
  build:
  
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        goarch: [amd64, arm64, arm]
        include:
          - os: ubuntu-latest
            goarch: amd64
          - os: ubuntu-latest
            goarch: arm64
          - os: ubuntu-latest
            goarch: arm
          - os: macos-latest
            goarch: amd64
          - os: macos-latest
            goarch: arm64
          - os: windows-latest
            goarch: amd64
          - os: windows-latest
            goarch: arm64

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Make
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            GOOS=windows go build -o output/FolderSum_${{ matrix.goarch }}.exe main.go
          else
            GOOS=${{ matrix.os == 'macos-latest' && 'darwin' || 'linux' }} go build -o output/FolderSum_${{ matrix.goarch }} main.go
          fi

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/FolderSum_${{ matrix.goarch }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
