name: Build Go Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        arch:
          - amd64
          - arm64
          - armv7

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20' # Specify your Go version

      - name: Build
        run: |
          # Set GOOS and GOARCH based on the matrix values
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            ext=".exe"
          else
            ext=""
          fi

          GOOS=${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'macos-latest' && 'darwin' || 'windows' }}
          GOARCH=${{ matrix.arch }}

          echo "Building for $GOOS/$GOARCH"
          env GOOS=$GOOS GOARCH=$GOARCH go build -o output/${{ github.event_name }}_${GOOS}_${GOARCH}${ext}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-executables
          path: output/
