name: Build and Release ARMv7

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Make ARMv7
        working-directory: .
        run: GOOS=linux GOARCH=arm GOARM=7 go build -o output/FolderSum_armv7 main.go
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/FolderSum_armv7
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
