name: Build and Release i386

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Make ARM64
        working-directory: .
        run: GOOS=linux GOARCH=386 go build -o output/FolderSum_386 main.go
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/FolderSum_386
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
