name: Build and Release macOS ARM64

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Make macOS ARM64
        working-directory: .
        run: GOOS=darwin GOARCH=arm64 go build -o output/FolderSum_darwin_arm64 main.go
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/FolderSum_darwin_arm64
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
